version: '3.7'

services:
  db:
    image: mongo:4.0-xenial
    environment:
      MONGO_INITDB_ROOT_USERNAME: jambo
      MONGO_INITDB_ROOT_PASSWORD: jambo

  server:
    build: ./server
    command: sh -c "yarn install --frozen-lockfile && yarn start"
    environment:
      DATABASE_URL: mongodb://jambo:jambo@db:27017/jambo
      PORT: 5000
    volumes:
      - ./server:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - db

  client:
    build: ./client
    command: sh -c "yarn install --frozen-lockfile && yarn start"
    volumes:
      - ./client:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - server
