version: '3'

services:
  server:
    build: ./server
    command: sh -c "yarn install --frozen-lockfile && yarn start"
    volumes:
      - ./server:/usr/src/app
    ports:
      - "5000:3000"
  client:
    build: ./client
    command: sh -c "yarn install --frozen-lockfile && yarn start"
    volumes:
      - ./client:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - server
